[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run prisma:generate']

[start]
cmd = 'tsx src/server.ts'

[variables]
NODE_ENV = 'production'
